### ISSUE TITLE
Django Secret Key should not appear in the repository

### ISSUE THREAD

**Issue by sattisvar** [primairepopulaire/unionGov#1]
https://github.com/primairepopulaire/unionGov/blob/master/unionGov/unionGov/settings.py#L23

It is best practice to have this secret key set in environment variable and read from there, instead of having it plain in `settings.py`
This must be done before going into production.

**Comment by Moali97** [comment]
Yes it should not appear in the repository during production. I put mine in an .env file also put my database information in the .env file such as username, password etc as you do not want this to be visible.

**Comment by SoGar-code** [comment]
Thank you for your comment! I have created a new branch to fix the issue. I have added a point in the README regarding the `.env` file. 

It seems at that point in the project, changing the secret key has not much consequences, so you can create your own `.env` file with the secret key of your choice!
